"""Test suite for OpenTelemetry distributed tracing, context propagation, and trajectory evaluations."""

import sys
import os
import asyncio
import unittest

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from agents.telemetry import (
    get_tracer,
    inject_trace_context,
    extract_trace_context,
    get_trajectory_recorder,
    setup_telemetry
)
from agents.bus_runtime import MAFMessageBusManager
from agents.evaluations import SwarmTrajectoryEvaluator
from agents.memory import LongTermMemoryManager


class TestOpenTelemetryObservability(unittest.IsolatedAsyncioTestCase):

    async def asyncSetUp(self):
        setup_telemetry()
        self.recorder = get_trajectory_recorder()
        self.recorder.clear()
        self.bus_manager = MAFMessageBusManager()
        await self.bus_manager.initialize_and_start()

    async def asyncTearDown(self):
        await self.bus_manager.shutdown()

    async def test_w3c_context_propagation(self):
        """Verify W3C traceparent injection and extraction across boundaries."""
        tracer = get_tracer("test.w3c")
        with tracer.start_as_current_span("parent_span") as parent:
            carrier = inject_trace_context({})
            self.assertIn("traceparent", carrier)
            trace_id_hex = format(parent.get_span_context().trace_id, "032x")
            self.assertIn(trace_id_hex, carrier["traceparent"])

            # Extract in simulated remote microservice
            extracted_ctx = extract_trace_context(carrier)
            self.assertIsNotNone(extracted_ctx)
            print("\n[Test] W3C Trace Context successfully injected and extracted across boundaries!")

    async def test_end_to_end_instrumented_trajectory(self):
        """Verify full execution graph generated by MAF message bus and evaluated by TrajectoryEvaluator."""
        print("\n[Test] Executing MAF message bus with live OpenTelemetry tracing...")
        query = "Has customer Acme Corp's laptop order shipped?"
        response = await self.bus_manager.send_user_query(query)

        self.assertTrue(response.is_shipped)
        self.assertIsNotNone(response.trace_id)

        # Inspect collected spans
        spans = self.recorder.get_finished_spans()
        span_names = [s.name for s in spans]
        print(f"\n[Recorded Spans ({len(spans)})]:")
        for s in spans:
            dur = ((s.end_time - s.start_time) / 1_000_000) if s.end_time and s.start_time else 0.0
            print(f"  • {s.name:<38} [SpanID: {format(s.context.span_id, '016x')}] [{dur:.1f}ms]")

        # Verify key cognitive reasoning & MCP tool spans exist
        self.assertIn("planner_strategic_orchestration", span_names)
        self.assertIn("erp_agent_reasoning", span_names)
        self.assertIn("mcp_tool_execute_read_query_db_01", span_names)
        self.assertIn("wms_agent_reasoning", span_names)
        self.assertIn("mcp_tool_execute_read_query_db_02", span_names)
        self.assertIn("tms_agent_reasoning", span_names)
        self.assertIn("mcp_tool_execute_read_query_db_03", span_names)
        self.assertIn("planner_fact_synthesis", span_names)

        # Evaluate trajectory with SwarmTrajectoryEvaluator
        evaluator = SwarmTrajectoryEvaluator()
        scorecard = evaluator.evaluate_trajectory(response)

        print("\n" + "=" * 70)
        print("📋 TRAJECTORY EVALUATION SCORECARD (LLM-as-a-Judge)")
        print("=" * 70)
        print(f"Session ID:                 {scorecard.session_id}")
        print(f"Trace ID:                   {scorecard.trace_id}")
        print(f"Total Spans:                {scorecard.total_spans_recorded}")
        print(f"Trajectory Completeness:    {scorecard.trajectory_completeness_score * 100:.1f}%")
        print(f"Context Propagation:        {scorecard.context_propagation_score * 100:.1f}%")
        print(f"Domain Isolation:           {scorecard.domain_isolation_score * 100:.1f}%")
        print(f"Fact Grounding:             {scorecard.fact_grounding_score * 100:.1f}%")
        print(f"Overall Weighted Score:     {scorecard.overall_score * 100:.1f}%")
        print(f"Verdict:                    {scorecard.verdict}")
        print("=" * 70)

        self.assertEqual(scorecard.verdict, "PASSED")
        self.assertGreaterEqual(scorecard.overall_score, 0.95)

    async def test_long_term_memory_persistence(self):
        """Verify long-term memory checkpointing and cross-session recall."""
        print("\n[Test] Testing Long-Term Memory persistence and recall...")
        mem_mgr = LongTermMemoryManager()

        rec = await mem_mgr.persist_session_memory(
            session_id="session_acme_9921",
            user_query="Has customer Acme Corp's laptop order shipped?",
            order_id="SO-10045",
            customer_name="Acme Corp",
            handling_unit_id="HU-8841-PLT",
            tracking_number="TRK-AFX-9948201",
            is_shipped=True,
            final_answer="Order shipped via Apex Freight Express",
            trace_id="4bf92f3577b34da6a3ce929d0e0e4736"
        )
        self.assertEqual(rec.order_id, "SO-10045")

        # Recall by session ID
        recalled = await mem_mgr.recall_session("session_acme_9921")
        self.assertIsNotNone(recalled)
        self.assertEqual(recalled.tracking_number, "TRK-AFX-9948201")

        # Search by customer
        history = await mem_mgr.search_memory_by_customer("Acme")
        self.assertEqual(len(history), 1)
        self.assertEqual(history[0].order_id, "SO-10045")
        print("  -> Passed: Long-term memory checkpointed and recalled successfully!")


if __name__ == "__main__":
    unittest.main()
